package uz.softex.carsale.position.entity

enum class Permissions {
    DELETE_USERS,
    UPDATE_POSITION,
    UPDATE_USERS,
    GET_USERS_BY_ID,
    GET_ALL_USERS_BY_COMPANY,
    ENABLE_USERS,

    ADD_POSITION,
    GET_POSITION,
    DELETE_CAR_MODEL,
    ADD_CAR_MODEL,
    DELETE_CAR,
    ADD_CAR,
    ADD_CAR_PHOTO,
    ADD_ADDRESS,
    DELETE_CONTRACT,
    BUY,
    GET_CONTRACTS,
    COMPANY,
    UPDATE_COMPANY
}